name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  deployments: write
  pull-requests: write
  issues: write

jobs:
  ci:
    uses: batumi-works/cf-pipeline/.github/workflows/ci.yml@v1
    with:
      node_version: '18'
      wrangler_version: 'latest'
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      enable_security_scan: true
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}

  deploy:
    uses: batumi-works/cf-pipeline/.github/workflows/deploy.yml@v1
    needs: ci
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      node_version: '18'
      wrangler_version: 'latest'
      dry_run: false
      enable_rollback: true
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}